import Image from 'next/image'
import { assetPath } from '@/lib/site-config'
import Link from 'next/link'
import { services } from '@/lib/site-config'
import { ServiceCard } from '@/components/service-card'
import { PortfolioGrid } from '@/components/portfolio-grid'
import { SectionHeading } from '@/components/section-heading'
import { InquiryForm } from '@/components/inquiry-form'
import { ArrowIcon } from '@/components/icons'

export default function Home(){return <>
<section className="relative overflow-hidden bg-[#2c2224] text-white">
 <div className="absolute inset-0"><Image src={assetPath('/images/couple-prewedding.jpeg')} alt="Couple photographed by TINA Photo Solutions" fill priority sizes="100vw" className="object-cover object-[54%_42%] opacity-75"/><div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/40 to-black/5"/></div>
 <div className="container-page relative flex min-h-[68svh] items-end py-12 sm:min-h-[72vh] sm:items-center sm:py-20">
  <div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.24em] text-white/80">Tokyo-based • English-friendly • Personal & event photography</p><h1 className="mt-4 text-5xl leading-[.95] sm:text-7xl lg:text-8xl">Your Tokyo Moments, Beautifully Captured.</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/85 sm:text-lg">Professional photography for couples, families, visitors and special occasions across Tokyo.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/book" className="btn-primary">Reserve a Photoshoot</Link><Link href="/portfolio" className="btn-secondary !border-white/20 !bg-white/10 !text-white">View Portfolio</Link></div></div>
 </div>
</section>

<section className="container-page py-20 sm:py-28"><SectionHeading eyebrow="Choose your session" title="Photography for the moments you came to Tokyo for." copy="From a private travel shoot to a company dinner, every session is planned around the people, atmosphere and photographs you want to come away with."/><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{services.map(s=><ServiceCard key={s.slug} {...s}/>)}</div></section>

<section className="bg-white py-20 sm:py-28"><div className="container-page"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHeading eyebrow="Portfolio" title="Real people. Real occasions. Tokyo as the backdrop."/>
{/* <Link href="/portfolio" className="inline-flex items-center gap-2 font-semibold text-brand">Explore the portfolio <ArrowIcon/></Link> */}
</div><div className="mt-10"><PortfolioGrid compact/></div></div></section>

<section className="petals py-20 sm:py-28"><div className="container-page grid gap-10 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="relative aspect-[4/5] overflow-hidden rounded-4xl"><Image src={assetPath('/images/cherry-blossom-portrait.jpeg')} alt="Tokyo seasonal portrait among cherry blossoms" fill sizes="(min-width:1024px) 45vw,100vw" className="object-cover"/></div><div><p className="eyebrow">For visitors to Japan</p><h2 className="section-title">Your Personal Photographer in Tokyo</h2><p className="body-copy mt-5">Whether you’re visiting Japan for the first time, celebrating an anniversary, wearing kimono for the day, or simply want beautiful photographs of your Tokyo experience, I’ll help you create relaxed, natural images you’ll want to keep.</p><p className="mt-5 text-sm leading-7 text-muted">Sessions can be planned around traditional streets, parks and gardens, seasonal blossom areas, modern city scenes, nighttime Tokyo, and temple or shrine surroundings where photography is permitted.</p><Link href="/book" className="btn-primary mt-7">Plan Your Tokyo Photoshoot</Link></div></div></section>

<section className="bg-[#2b2224] py-20 text-white sm:py-28"><div className="container-page"><SectionHeading eyebrow="How it works" title="Simple from first message to final gallery." copy="The booking flow is designed to be easy from your phone, whether you live in Tokyo or are planning your trip from overseas."/><div className="mt-10 grid gap-4 md:grid-cols-4">{[['01','Send an enquiry','Tell me the type of shoot you have in mind.'],['02','Choose the details','Share your preferred date, location and style.'],['03','Confirm your session','Agree the session details before the shoot.'],['04','Meet in Tokyo','Enjoy the shoot. Edited photographs are delivered digitally afterward.']].map(([n,t,c])=><div key={n} className="rounded-3xl border border-white/10 bg-white/5 p-6"><span className="text-sm font-semibold text-rose">{n}</span><h3 className="mt-8 text-2xl">{t}</h3><p className="mt-2 text-sm leading-6 text-white/65">{c}</p></div>)}</div></div></section>

<section id="about" className="container-page py-20 sm:py-28"><div className="grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">About the photographer</p><h2 className="section-title">Photography should feel comfortable, natural and enjoyable.</h2><p className="body-copy mt-5">TINA Photo Solutions focuses on helping people preserve important moments without making the experience feel overly staged. Sessions are shaped around your occasion, who you are with, and the atmosphere you want.</p><p className="mt-5 rounded-3xl border border-dashed border-brand/25 bg-white p-5 text-sm text-muted"><strong className="text-ink">Editable biography area:</strong> add the photographer’s factual background, approach and portrait here when ready.</p></div><div className="grid gap-4 sm:grid-cols-2">{['Personalised photography sessions','Tokyo location experience','English-friendly communication','Relaxed posing guidance','Individuals, couples, families & events','Professionally edited digital images','Flexible session planning'].map(x=><div key={x} className="rounded-3xl border bg-white p-5 text-sm font-semibold">{x}</div>)}</div></div></section>

<section className="bg-blush/70 py-20 sm:py-28"><div className="container-page"><SectionHeading eyebrow="Client feedback" title="Trust, in their own words." copy="No reviews are fabricated. Connect verified Google reviews, Instagram comments or client testimonials here when available."/><div className="mt-8 grid gap-4 md:grid-cols-3">{[1,2,3].map(n=><div key={n} className="rounded-3xl border border-dashed border-black/15 bg-white/70 p-7"><p className="text-sm font-medium">Client testimonial placeholder</p><p className="mt-3 text-sm leading-6 text-muted">Replace this card with a real, permissioned client review.</p></div>)}</div></div></section>

<section id="faq" className="container-page py-20 sm:py-28"><SectionHeading eyebrow="FAQ" title="Questions before you book"/><div className="mt-10 grid gap-3 lg:grid-cols-2">{[
['Where do you photograph in Tokyo?','Locations are planned around your session style, timing and any access restrictions. Tell me the atmosphere you want and we can discuss suitable Tokyo options.'],['Can tourists book a photoshoot?','Yes. The site and enquiry flow are designed for both Tokyo residents and visitors planning a trip to Japan.'],['Can I book a kimono photoshoot?','Yes. You can enquire for a kimono photography session in Tokyo.'],['Do you provide the kimono?','Kimono rental is not currently listed as an included service. Please arrange your own rental unless a partnership or package is confirmed with you.'],['What happens if it rains?','Weather and rescheduling policy: add the photographer’s confirmed policy here.'],['Can you photograph surprise proposals?','Yes. The plan, timing and photographer position can be discussed discreetly before the day.'],['Can families and children book?','Yes. Birthday, child and family photography are part of the current service range.'],['Do you photograph corporate events?','Yes. Event photography can cover corporate gatherings, dinners and networking events.'],['How many photos will I receive?','Image count depends on the package. Add confirmed package details here when pricing is finalised.'],['How long does editing take?','Delivery time: add the photographer’s confirmed turnaround here.'],['Can I choose the location?','Yes, location preferences can be discussed, subject to practical access and photography restrictions.'],['Do you speak English?','English-friendly communication is available.']
].map(([q,a])=><details key={q} className="group rounded-3xl border bg-white p-5"><summary className="cursor-pointer list-none font-semibold">{q}<span className="float-right text-brand group-open:rotate-45">＋</span></summary><p className="mt-4 text-sm leading-6 text-muted">{a}</p></details>)}</div></section>

<section className="bg-white py-20 sm:py-28"><div className="container-page grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Ready to capture your Tokyo story?</p><h2 className="section-title">Tell me what you’re planning.</h2><p className="body-copy mt-5">I’ll help you shape a photoshoot that fits the occasion, the people and the Tokyo atmosphere you want.</p></div><div className="card p-6 sm:p-8"><InquiryForm compact/></div></div></section>
</>}
