import Image from 'next/image'
import Link from 'next/link'
import { InquiryForm } from './inquiry-form'

type Props={eyebrow:string;title:string;description:string;image?:string;imageAlt?:string;bullets:string[];note?:string}
export function ServiceLanding({eyebrow,title,description,image,imageAlt,bullets,note}:Props){return <>
<section className="container-page py-12 sm:py-20"><div className="grid overflow-hidden rounded-4xl border bg-white shadow-soft lg:grid-cols-2"><div className="relative min-h-[430px] bg-[#21181b]">{image?<Image src={image} alt={imageAlt||title} fill priority sizes="(min-width:1024px) 50vw,100vw" className="object-cover"/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_25%,rgba(201,22,29,.38),transparent_25%),linear-gradient(145deg,#171114,#43262d,#171114)]"/>}</div><div className="p-7 sm:p-10 lg:p-14"><p className="eyebrow">{eyebrow}</p><h1 className="mt-3 text-5xl leading-[.98] sm:text-6xl">{title}</h1><p className="body-copy mt-5">{description}</p><ul className="mt-7 grid gap-3 text-sm leading-6 text-muted">{bullets.map(x=><li key={x} className="rounded-2xl bg-blush/70 px-4 py-3">{x}</li>)}</ul>{note&&<p className="mt-5 text-sm leading-6 text-muted">{note}</p>}<Link href="/book" className="btn-primary mt-7">Reserve a Photoshoot</Link></div></div></section>
<section className="bg-white py-16 sm:py-24"><div className="container-page grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Enquire</p><h2 className="section-title">Plan your session in a few details.</h2><p className="body-copy mt-5">Share your date, group size and preferred area. Specific locations remain subject to practical access and photography permissions.</p></div><div className="card p-6 sm:p-8"><InquiryForm compact/></div></div></section>
</>}
